version: '3'
services:
    rss-feed-bff:
        build:
            dockerfile: Dockerfile
        ports:
            - 4000:4000
        environment:
            PORT: 4000
        volumes:
            - ".:/rss-feed"
