// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Link      string  `json:"link"`
	Media     *Media  `json:"media"`
	Title     string  `json:"title"`
	Author    *Author `json:"author"`
	Updated   string  `json:"updated"`
	Published string  `json:"published"`
}

type Author struct {
	URI  string `json:"uri"`
	Name string `json:"name"`
}

type Community struct {
	StarRating *StarRating `json:"starRating"`
	Statistics *Statistics `json:"statistics"`
}

type Content struct {
	URL    string `json:"url"`
	Type   string `json:"type"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

type Feed struct {
	ID        string  `json:"id"`
	URL       string  `json:"url"`
	Link      string  `json:"link"`
	Title     string  `json:"title"`
	Author    *Author `json:"author"`
	Published string  `json:"published"`
}

type Media struct {
	Title       string     `json:"title"`
	Content     *Content   `json:"content"`
	Thumbnail   *Thumbnail `json:"thumbnail"`
	Description string     `json:"description"`
	Community   *Community `json:"community"`
}

type StarRating struct {
	Count   int     `json:"count"`
	Average float64 `json:"average"`
	Min     int     `json:"min"`
	Max     int     `json:"max"`
}

type Statistics struct {
	Views int `json:"views"`
}

type Thumbnail struct {
	URL    string `json:"url"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}
