package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"rss/graph/model"
)

// RemoveElement is the resolver for the removeElement field.
func (r *mutationResolver) RemoveElement(ctx context.Context, id *string) (*bool, error) {
	panic(fmt.Errorf("not implemented: RemoveElement - removeElement"))
}

// Feeds is the resolver for the feeds field.
func (r *queryResolver) Feeds(ctx context.Context) ([]*model.Feed, error) {
	return r.Resolver.Feed.List(ctx), nil
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context, url *string) ([]*model.Article, error) {
	return r.Resolver.Article.List(ctx, url), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
